name: Fix PHP code style issues

on:
  push:
    paths:
      - '**.php'

permissions:
  contents: write
  pull-requests: write

jobs:
  php-code-styling:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fix PHP code style issues
        uses: aglipanci/laravel-pint-action@2.4

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Fix PHP code styling issues"
          branch: "auto-styling-branch"
          commit_user_name: "GitHub Actions"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions <actions@github.com>"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Fix PHP code styling issues"
          title: "Automated PHP code style fixes"
          body: "This PR includes automated PHP code style fixes."
          branch: "auto-styling-branch"
          delete-branch-after-merge: true

      - name: Auto-merge PR
        uses: pascalgn/automerge-action@v0.14.3
        if: github.ref == 'refs/heads/main'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: "merge"
          commit-message: "Merge PHP style fixes"
          pr-labels: "automerge"
          pr-comment: "Automerge approved: Code style checks passed"
